# Практическая работа к Уроку 4. Системы линейных уравнений

## Часть 1

**1. Решить систему уравнений методом Гаусса:**

$$\begin{cases} x_{1}+x_{2}-x_{3}-2x_{4}=0, \\ 2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\ x_{1}+x_{2}-3x_{3}+x_{4}=4. \end{cases}$$
Преобразуем расширенную матрицу системы путем элементарных преобразований:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 1 & -1 & -2 \\ 2 & 1 & -1 & 1 \\ 1 & 1 & -3 & 1 \end{matrix}\right| \begin{matrix} 0\\ -2\\ 4 \end{matrix} \end{pmatrix}$$
Отнимем из второй строки первую, умноженную на 2:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 1 & -1 & -2\\ 0 & -1 & 1 &5\\ 1 & 1 & -3 & 1 \end{matrix}\right| \begin{matrix} 0\\ -2\\ 4 \end{matrix} \end{pmatrix}$$
Отнимем из третьей строки первую:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 1 & -1 & -2\\ 0 & -1 & 1 & 5\\ 0 & 0 & -2 & 3 \end{matrix}\right| \begin{matrix} 0\\ -2\\ 4 \end{matrix} \end{pmatrix}$$
Система имеет бесконечное кол-во решений.
Поделим третью строку на 3:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 1 & -1 & -2\\ 0 & -1 & 1 & 5\\ 0 & 0 & -\frac{2}{3} & 1 \end{matrix}\right| \begin{matrix} 0\\ -2\\ \frac{4}{3} \end{matrix} \end{pmatrix}$$
Оставшаяся матрица соответствует системе:
$$\begin{cases} x_{1} + x_{2} - x_{3} -2 \cdot x_{4} = 0, \\ -x_{2} + x_{3} + 5 \cdot x_{4} = -2, \\ -\frac{2}{3} \cdot x_{3} + x_{4} = \frac{4}{3} \end{cases}$$
Бесконечное множество решений принято записывать в виде общего решения.
Последнее уравнение содержит две неизвестных. В данном случае можно рассматривать в качестве свободного параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:
$x_{4}=c,$
$x_{3}=\frac{4-3c}{-2} \;$
$x_{2}=2 + 5 \cdot c + \frac{4-3c}{-2},$
$x_{1}=-2 -3 \cdot c.$
Таковым будет общее решение системы. Подставляя произвольные числа вместо $c$, мы получим частное решение. Например, при $c=0$:
$x_{1}=-2,$ $x_{2}=0,$ $x_{3}=-2,$ $x_{4}=0.$
Параметр $c$ может принимать бесконечное количество значений, при которых уравнения в системе будут обращаться в тождества.

**2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:**

__а)__ $\begin{cases} 3x_{1}-x_{2}+x_{3}=4, \\ 2x_{1}-5x_{2}-3x_{3}=-17, \\ x_{1}+x_{2}-x_{3}=0; \end{cases}$

$$\begin{pmatrix} \left.\begin{matrix} 3 & -1 & 1 \\ 2 & -5 & -3 \\ 1 & 1 & -1 \end{matrix}\right| \begin{matrix} 4\\ -17\\ 0 \end{matrix} \end{pmatrix}$$
Поделим первую строку на 3:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -\frac{1}{3} & \frac{1}{3} \\ 2 & -5 & -3 \\ 1 & 1 & -1 \end{matrix}\right| \begin{matrix} \frac{4}{3}\\ -17\\ 0 \end{matrix} \end{pmatrix}$$
Отнимем из второй строки первую, умноженную на 2:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -\frac{1}{3} & \frac{1}{3} \\ 0 & -\frac{13}{3} & -\frac{11}{3} \\ 1 & 1 & -1 \end{matrix}\right| \begin{matrix} \frac{4}{3}\\ -\frac{59}{3}\\ 0 \end{matrix} \end{pmatrix}$$
Отнимем из третьей строки первую:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -\frac{1}{3} & \frac{1}{3} \\ 0 & -\frac{13}{3} & -\frac{11}{3} \\ 0 & \frac{4}{3} & -\frac{4}{3} \end{matrix}\right| \begin{matrix} \frac{4}{3}\\ -\frac{59}{3}\\ -\frac{4}{3} \end{matrix} \end{pmatrix}$$
Умножим вторую строку на $-\frac{3}{13}$, и отнимем вторую строку из третьей:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -\frac{1}{3} & \frac{1}{3} \\ 0 & 1 & \frac{11}{13} \\ 0 & 0 & \frac{24}{13} \end{matrix}\right| \begin{matrix} \frac{4}{3}\\ \frac{59}{13}\\ \frac{72}{13} \end{matrix} \end{pmatrix}$$
Упростим третью строку, путем умножения на 13 и деления полученных значений на 24:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -\frac{1}{3} & \frac{1}{3} \\ 0 & 1 & \frac{11}{13} \\ 0 & 0 & 1 \end{matrix}\right| \begin{matrix} \frac{4}{3}\\ \frac{59}{13}\\ 3 \end{matrix} \end{pmatrix}$$
$rangA=rang(A|B)=n$, следовательно, система совместная и определенная



__б)__ $\begin{cases} 2x_{1}-4x_{2}+6x_{3}=1, \\ x_{1}-2x_{2}+3x_{3}=-2, \\ 3x_{1}-6x_{2}+9x_{3}=5; \end{cases}$


$$\begin{pmatrix} \left.\begin{matrix} 2 & -4 & 6 \\ 1 & -2 & 3 \\ 3 & 6 & -9 \end{matrix}\right| \begin{matrix} 1\\ -2\\ 5 \end{matrix} \end{pmatrix}$$
Поделим первую строку на 2:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -2 & 3 \\ 1 & -2 & 3 \\ 3 & 6 & -9 \end{matrix}\right| \begin{matrix} 0.5\\ -2\\ 5 \end{matrix} \end{pmatrix}$$
Отнимем из второй строки первую:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -2 & 3 \\ 0 & 0 & 0 \\ 3 & 6 & -9 \end{matrix}\right| \begin{matrix} 0.5\\ -2.5\\ 5 \end{matrix} \end{pmatrix}$$
Отнимем из третьей строки первую, умноженную на 3:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -2 & 3 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{matrix}\right| \begin{matrix} 0.5\\ -2.5\\ 3.5 \end{matrix} \end{pmatrix}$$
Поделим вторую строку на -2.5:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -2 & 3 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{matrix}\right| \begin{matrix} 0.5\\ 1\\ 3.5 \end{matrix} \end{pmatrix}$$
Отнимем из третьей строки вторую, умноженную на 3.5:
$$\begin{pmatrix} \left.\begin{matrix} 1 & -2 & 3 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{matrix}\right| \begin{matrix} 0.5\\ 1\\ 0 \end{matrix} \end{pmatrix}$$
$rangA$ не равен $rang(A|B)$, следовательно, система несовместная


__в)__ $\begin{cases} x_{1}+2x_{2}+5x_{3}=4, \\ 3x_{1}+x_{2}-8x_{3}=-2. \end{cases}$

$$\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 5 \\ 3 & 1 & -8 \end{matrix}\right| \begin{matrix} 4\\ -2 \end{matrix} \end{pmatrix}$$
Отнимем из второй строки первую, умноженную на 3:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 5 \\ 0 & -5 & -23 \end{matrix}\right| \begin{matrix} 4\\ -14 \end{matrix} \end{pmatrix}$$
Разделим вторую строку на -5:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 5 \\ 0 & 1 & \frac{23}{5} \end{matrix}\right| \begin{matrix} 4\\ \frac{14}{5} \end{matrix} \end{pmatrix}$$
$rangA=rang(A|B)<n$, следовательно, система совместная и неопределенная

**3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей**

$$\tilde{A}=\begin{pmatrix} \left.\begin{matrix} 1 & 3 & -2 & 4\\ 0 & 5 & 0 & 1\\ 0 & 0 & 3 & 0\\ 0 & 0 & 0 & 2 \end{matrix}\right| \begin{matrix} 3\\ 2\\ 4\\ 1 \end{matrix} \end{pmatrix}.$$
$rang(A)=rang(A|B)=n$, следовательно, система совместная и определенная

**4. Дана система линейных уравнений, заданная расширенной матрицей**

$$\tilde{A}=\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9 \end{matrix}\right| \begin{matrix} a\\ b\\ c \end{matrix} \end{pmatrix}.$$
Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.


Отнимем из второй строки первую, умноженную на 4:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 3\\ 0 & -3 & -6\\ 7 & 8 & 9 \end{matrix}\right| \begin{matrix} a\\ b-4 \cdot a\\ c \end{matrix} \end{pmatrix}$$
Отнимем из третьей строки первую, умноженную на 7:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 3\\ 0 & -3 & -6\\ 0 & -6 & -12 \end{matrix}\right| \begin{matrix} a\\ b-4 \cdot a\\ c-7 \cdot a \end{matrix} \end{pmatrix}$$
Отнимем из третьей строки вторую, умноженную на -2:
$$\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 3\\ 0 & -3 & -6\\ 0 & 0 & 0 \end{matrix}\right| \begin{matrix} a\\ b-4 \cdot a\\ c-7 \cdot a + 2\cdot b -8\cdot a \end{matrix} \end{pmatrix}$$

При $(-15 \cdot a + 2\cdot b + c)\neq0$ система является несовместной

## Часть 2

**5. Решить систему уравнений методом Крамера:**

__а)__ $\begin{cases} x_{1}-2x_{2}=1 \\ 3x_{1}-4x_{2}=7 \end{cases}$

Найдем определитель матрицы:
$detA=\begin{vmatrix} 1 & -2\\ 3 & -4\\ \end{vmatrix}=(1 \cdot -4) - (-2 \cdot 3) = 2$
Найдем определитель $detA_{1}$:
$detA_{1}=\begin{vmatrix} 1 & -2\\ 7 & -4\\ \end{vmatrix}=(1 \cdot -4) - (-2 \cdot 7) = 10$
Найдем определитель $detA_{2}$:
$detA_{2}=\begin{vmatrix} 1 & 1\\ 3 & 1\\ \end{vmatrix}=(1 \cdot 7) - (1 \cdot 3) = 4$
Найдем значения $x_{1}, x_{2}$:
$x_{1}=10/2=5$
$x_{2}=4/2=2$
Проверим полученное решение:
$\begin{cases} 5-4=1 \\ 15-8=7 \end{cases}$


__б)__ $\begin{cases} 2x_{1}-x_{2}+5x_{3}=10 \\ x_{1}+x_{2}-3x_{3}=-2 \\ 2x_{1}+4x_{2}+x_{3}=1 \end{cases}$

Найдем определитель матрицы:
$detA=\begin{vmatrix} 2 & -1 & 5\\ 1 & -1 & -3\\ 2 & 4 & 1 \end{vmatrix}=(2 \cdot 1 \cdot 1) + (-1 \cdot -3 \cdot 2) + (5 \cdot 1 \cdot 4) - (5 \cdot 1 \cdot 2) - (2 \cdot -3 \cdot 4) - (-1 \cdot 1 \cdot 1) = 43$
Найдем определитель $detA_{1}$:
$detA_{1}=\begin{vmatrix} 10 & -1 & 5\\ -2 & -1 & -3\\ 1 & 4 & 1 \end{vmatrix}=(10 \cdot 1 \cdot 1) + (-1 \cdot -3 \cdot 1) + (5 \cdot -2 \cdot 4) - (5 \cdot 1 \cdot 1) - (10 \cdot -3 \cdot 4) - (-1 \cdot -2 \cdot 1) = 86$
Найдем определитель $detA_{2}$:
$detA_{2}=\begin{vmatrix} 2 & 10 & 5\\ 1 & -2 & -3\\ 2 & 1 & 1 \end{vmatrix}=(2 \cdot -2 \cdot 1) + (10 \cdot -3 \cdot 2) + (5 \cdot 1 \cdot 1) - (5 \cdot -2 \cdot 2) - (2 \cdot -3 \cdot 1) - (10 \cdot 1 \cdot 1) = -43$
Найдем определитель $detA_{3}$:
$detA_{3}=\begin{vmatrix} 2 & -1 & 10\\ 1 & -1 & -2\\ 2 & 4 & 1 \end{vmatrix}=(2 \cdot 1 \cdot 1) + (-1 \cdot -2 \cdot 2) + (10 \cdot 1 \cdot 4) - (10 \cdot 1 \cdot 2) - (2 \cdot -2 \cdot 4) - (-1 \cdot 1 \cdot 1) = 43$
Найдем значения $x_{1}, x_{2}, x_{3}$:
$x_{1}=86/43=2$
$x_{2}=-43/43=-1$
$x_{3}=43/43=1$
Проверим полученное решение:
$\begin{cases} 4+1+5=10 \\ 2-1-3=-2 \\ 4-4+1=1 \end{cases}$

**2*. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:**

а)$$\begin{pmatrix} 1 & 2 & 4 \\ 2 & 9 & 12 \\ 3 & 26 & 30 \end{pmatrix}$$

б)$$\begin{pmatrix} 1 & 1 & 2 & 4\\ 2 & 5 & 8 & 9\\ 3 & 18 & 29 & 18\\ 4 & 22 & 53 & 33 \end{pmatrix}$$



Умножаем первую строчку на 2 и 3 и вычитаем соответственно из 2 и 3 строки. Подставляем в L значения 2 и 3. Умножаем вторую сторочку на 5 и вычитаем из 3. Подставляем значение 5. Мы получили верхнетреуглльную и нижнетреугольную матрицы.

In [1]:
import numpy as np
from scipy.linalg import lu
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = lu(A)
B = P.dot(L).dot(U)
print(B)
print('L-матрица:')
print(L)

[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]
L-матрица:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


3*. Решить систему линейных уравнений методом $LU$-разложения
$$\begin{cases} 2x_{1}+x_{2}+3x_{3}=1 \\ 11x_{1}+7x_{2}+5x_{3}=-6 \\ 9x_{1}+8x_{2}+4x_{3}=-5 \end{cases}$$



Матрица коэффициентов $A$ будет иметь вид
$$\begin{pmatrix} 2 & 1 & 3 \\ 11 & 7 & 5 \\ 9 & 8 & 4 \end{pmatrix}.$$

Начнем прямой ход метода Гаусса:
$$\begin{pmatrix} 2 & 1 & 3 \\ 0 & \frac{3}{2} & \frac{-23}{2} \\ 0 & 0 & \frac{52}{3} \end{pmatrix}.$$
Матрица L - $$L=\begin{pmatrix} 1 & 0 & 0 \\ \frac{11}{2} & 1 & 0 \\ \frac{9}{2} & \frac{7}{2} & 1 \end{pmatrix}.$$
Матрица U -
$$U=\begin{pmatrix} 2 & 1 & 3 \\ 0 & 3 & -23 \\ 0 & 0 & \frac{52}{9} \end{pmatrix},$$

Решим теперь систему $Ly=b:$
$$\begin{cases} y_{1}=1, \\ \frac{11}{2}y_{1}+y_{2}=-6, \\ \frac{9}{2}y_{1}+ \frac{7}{2}y_{2}+y_{3}=-5. \end{cases}$$$$y_{1} = 1,$$$$y_{2}=-6 -\frac{11}{2} =11.5$$$$y_{3}=-5-\frac{9}{2} - \frac{7}{2}=-13.$$

И затем систему
$$x_1 = -1$$
Произведем проверку, подставив полученные значения переменных в исходную систему:$$\begin{cases} 2(-1)+3=1 \\ 11(-1)+5=-6 \\ 9(-1)+4=-5 \end{cases}$$

**4*. Решить систему линейных уравнений методом Холецкого**
$$\begin{cases} 81x_{1}-45x_{2}+45x_{3}=531 \\ -45x_{1}+50x_{2}-15x_{3}=-460 \\ 45x_{1}-15x_{2}+38x_{3}=193 \end{cases}$$



In [2]:
from numpy.linalg import cholesky
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
L = cholesky(A)
print(L)

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


Решим систему $Ly=b:$
$$\begin{cases} 9y_{1}=531, \\ -5y_{1}+5y_{2}=-460, \\ 5y_{1}+2y_{2}+3y_{3}=193. \end{cases}$$

In [3]:
print(L.T)

[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]


**5*. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.**

In [4]:
# Минор
def submatrix(M,c):
    B = [[1]*len(M) for i in range(len(M))]
    for l in range(len(M)):
        for k in range(len(M)):
            B[l][k] = M[l][k]
    
    B.pop(0)
    
    for i in range(len(B)):
        B[i].pop(c)
    return B

# Метод Лапласа
def det_L(M):
    X = 0
    if len(M) != len(M[0]):
        print('Матрица не квадратная')
    else:
        if len(M)<=2:
            return M[0][0] * M[1][1] - M[0][1] * M[1][0]
        else:
            for i in range(len(M)):
                X = X + ((-1)**i)*M[0][i]*det_L(submatrix(M,i))
        return X

# Метод Крамера
def Kramer(A,B):
    det_A = det_L(A)
    X = []
    if det_A == 0:
        print('Определитель матрицы не должен быть равен 0')
        return X
    n = len(A)    
    for i in range(n):
        matrix = A.copy()
        matrix[:,i] = B
        print('\n',matrix)
        X.append(det_L(matrix) / det_A)
    return X

In [5]:
a = np.array([[43, 876, -29], [45, 98, 0], [-12, 0, 3]])
b = np.array([[-88, 21, 90]])

print(a)
print('\n',b)
print('\n', det_L(a))
print('\n', Kramer(a,b))

print(f'\n {b},\n\
Метод Лапласа:\n {det_L(a)},\n\
Метод Крамера:\n {Kramer(a,b)}')

[[ 43 876 -29]
 [ 45  98   0]
 [-12   0   3]]

 [[-88  21  90]]

 -139722

 [[-88 876 -29]
 [ 21  98   0]
 [ 90   0   3]]

 [[ 43 -88 -29]
 [ 45  21   0]
 [-12  90   3]]

 [[ 43 876 -88]
 [ 45  98  21]
 [-12   0  90]]

 [-1.2504831021600034, 0.7884871387469403, 24.998067591359987]

 [[-88 876 -29]
 [ 21  98   0]
 [ 90   0   3]]

 [[ 43 -88 -29]
 [ 45  21   0]
 [-12  90   3]]

 [[ 43 876 -88]
 [ 45  98  21]
 [-12   0  90]]

 [[-88  21  90]],
Метод Лапласа:
 -139722,
Метод Крамера:
 [-1.2504831021600034, 0.7884871387469403, 24.998067591359987]
