# Практическая работа к Уроку 2. Матрицы и матричные операции

In [1]:
import numpy as np

### Часть 1

**1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:**

 а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

***a)***
    
$A*B$ = $4\times 2$ и $4\times 2$

$B*A$ = $4\times 2$ и $4\times 2$

Произведения не определены


***б)***

$A*B$ = $2\times 5$ и $5\times 3$, произведение определено, размерность полученной матрицы $2\times 3$

$B*A$ = $5\times 3$ и $2\times 5$, произведение не определено


***в)***

$A*B$ = $8\times 3$ и $3\times 8$, произведение определено, размерность полученной матрицы $8\times 8$

$B*A$ = $3\times 8$ и $8\times 3$, произведение определено, размерность полученной матрицы $3\times 3$


***г)***

$A*B$, $B*A$ - оба произведения определены, размерность полученной матрицы $4\times 4$

**2. Найти сумму и произведение матриц**

$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0,5]])
result2_1 = a + b
result2_1

array([[ 5, -3],
       [ 3,  5]])

In [3]:
result2_2 = np.dot(a, b)
result2_2

array([[  4, -11],
       [ 12,  -3]])

**3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство.**

Вычислить линейную комбинацию  $3A-2B+4C$ для матриц 

$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, 

$B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, 

$C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [4]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
result3 = (3 * a) + (-2 * b) + (4 * c)
result3

array([[ 11,  -5],
       [  9, -12]])

**4. Дана матрица** 

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.


Вычислить $AA^{T}$ и $A^{T}A$.

In [5]:
a = np.array([[4,1], [5,-2], [2,3]])
aT = a.T
aT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [6]:
result4_1 = np.dot(a, aT)
result4_1

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
result4_2 = np.dot(aT, a)
result4_2

array([[45,  0],
       [ 0, 14]])

**5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**

In [8]:
def multiplication(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        return ValueError('произведение не определено')
    result = [ [0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

Проверка

In [14]:
x = np.array([[0,-9], [5,7], [3,2]])
y = np.array([[6,1], [-8,5]])
print(f'Матрица x:\n {x},\n\
Матрица y:\n {y},\n\
Результат с NumPy:\n {np.dot(x,y)},\n\
Результат без NumPy: \n {multiplication(x,y)}')

Матрица x:
 [[ 0 -9]
 [ 5  7]
 [ 3  2]],
Матрица y:
 [[ 6  1]
 [-8  5]],
Результат с NumPy:
 [[ 72 -45]
 [-26  40]
 [  2  13]],
Результат без NumPy: 
 [[72, -45], [-26, 40], [2, 13]]


### Часть 2

**1. Вычислить определитель:**

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

***а)***

$det = sinx * sinx - (cosx * -cosx) = sin^2x + cos^2x = 1$

***б)***

In [ ]:
a1_2 = np.array([[4,2,3], [0,5,1], [0,0,9]])
det1_2 = np.linalg.det(a1_2)
det1_2

***в)***

In [ ]:
a1_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
det1_3 = np.linalg.det(a1_3)
det1_3

**2. Определитель матрицы $A$ равен $4$. Найти:**

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

**а)**
$det(A^{2}) = det(AA) = det(A)*det(A) = 4 * 4 = 16$

**б)**
$det(A^{T}) = det(A) = 4$

**в)**
$det(2A) = det(A) * 2^n = 4 * 2^n$, n - кол-во строк в матрице

**3. Доказать, что матрица**

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [15]:
m = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
det3 = np.linalg.det(m)
det3

0.0

Поскольку определитель матрицы равен 0, матрица вырожденная.

**4. Найти ранг матрицы:**

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**a)**

In [16]:
m = np.array([[1,2,3], [1,1,1], [2,3,4]])
result4_1 = np.linalg.matrix_rank(m)
result4_1

2

**б)**

In [17]:
m = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
result4_2 = np.linalg.matrix_rank(m)
result4_2

3